### ISSUE TITLE
New pypi release?

### ISSUE THREAD

**Issue by rmmr** [graphql-python/graphql-ws#14]
The current pypi release is pretty outdated, especially the AiohttpSubscriptionServer. Would a new release be possible currently?

**Comment by fusion44** [comment]
I'd second that. Django channels support is not in latest pypi version.

**Comment by Dessix** [comment]
It appears that this is no longer accurate, as PyPI has been updated as of [September 25th 2018](https://pypi.org/project/graphql-ws/0.3.0/#files) and includes the `django_channels.py` file and other recent changes.

@syrusakbary this can probably be closed.
