### ISSUE TITLE
Bind subscriptions to mutations

### ISSUE THREAD

**Issue by Ouradze** [graphql-python/graphql-ws#20]
* GraphQL AioWS version: 0.3.0
* Python version: 3.6
* Operating System: ubuntu
* Django: 1.11
* Channels: 2.1

### Description

Hello, how would I do if I wanted to bind the subscription to an update from a mutation ? For instance, I would like to subscribe to the adding of a particular type of object, a sort of "AddObjectMutation". The example in the documentation is nice but quite far from a real usage.

Thanks in advance,

**Comment by ProjectCheshire** [comment]
This is more in the line of setting up general pubsub than graphene specific. For instance, I set up rabbitmq and create fan out channels that are broadcast to by mutations and listened to by subscriptions.

**Comment by SmileyChris** [comment]
projectcheshire's answer provides useful info, and this isn't an issue directly fixable by graphql-ws. If someone wanted to add docs that addressed this, go ahead, but for now I will close this issue
