### ISSUE TITLE
django-channels v2

### ISSUE THREAD

**Issue by xeor** [graphql-python/graphql-ws#23]
I'm baffled why I can't find any issues on using django-channels since channels have been out with v2 as default since february, and nor the example or the code is compatible..

There are a couple of pr's (https://github.com/graphql-python/graphql-ws/pull/18 and https://github.com/graphql-python/graphql-ws/pull/9), but none of them is merged..

Any status on when we will have a v2 compatible release? What is missing?

**Comment by bastiW** [comment]
https://github.com/graphql-python/graphql-ws/pull/9
Is merged

**Comment by xeor** [comment]
@bastiW is it? https://github.com/graphql-python/graphql-ws/pull/9 is closed in favor of https://github.com/graphql-python/graphql-ws/pull/18 (which is still open).. Anything I missed?

I retract my 🎉 emoji on you comment till you clearify 😆

**Comment by bastiW** [comment]
Oh sorry

My fault

Am Fr., 28. Dez. 2018, 11:15 hat Lars Solberg <notifications@github.com>
geschrieben:

**Comment by bastiW** [comment]
Oh sorry

My fault

**Comment by ryou90** [comment]
Here is the link to the related discussion about the future and maintainance of this project:
[graphql-python/graphene/issues/884]

**Comment by SmileyChris** [comment]
Merged to master!
