### ISSUE TITLE
AIOHTTP implementation imports but does not use inspect.isasyncgen; Breaks Python 3.5.x

### ISSUE THREAD

**Issue by Dessix** [graphql-python/graphql-ws#28]
* GraphQL-WS version: 3.0.0
* Python version: 3.5.6
* Operating System: Linux/Ubuntu18.04

### Description

Python 3.5.* cannot work with the current package contents because [PEP 525](https://www.python.org/dev/peps/pep-0525/) doesn't introduce `inspect.isasyncgen` until Python 3.6. This function is imported but never used, and injecting a fake version lets subscriptions work (but can have unintended consequences on other libraries).

### What I Did

It's just an import- try running it on Python 3.5.3+ with AIOHTTP if you need a repro.

**Comment by SmileyChris** [comment]
Was fixed in 9e7d46ddf4b77048a92520354c9d899c09defec8
