### ISSUE TITLE
Aiohttp example - can't connect from graphql playground

### ISSUE THREAD

**Issue by dtamez** [graphql-python/graphql-ws#33]
* GraphQL AioWS version: 0.3.0
* Python version: 3.6.5
* Operating System:  Linux - Ubuntu 18.04.2 LTS

### Description
Attempting to run the example aiohttp application and retrieve subscription information in graphql playground. 

### What I Did
I am running the example app via app.py in the examples/aiohttp directory.  
`python app.py`
Server starts and is listening on port 8000.  
I then start graphql playground and point it to http://localhost:8000/graphql.  
It retrieves the schema correctly as follows:
```
type Query {
  base: String
}

type RandomType {
  seconds: Int
  randomInt: Int
}

type Subscription {
  countSeconds(upTo: Int): Float
  randomInt: RandomType
}
```
I attempt to open up the websocket connection to listen for server updates via:
```
subscription {
   countSeconds
}
```
What happened:
The server logged the following output
```
Error handling request
Traceback (most recent call last):
  File "/home/danny/.virtualenvs/subs/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/danny/.virtualenvs/subs/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "./app.py", line 15, in graphql_view
    payload = await request.json()
  File "/home/danny/.virtualenvs/subs/lib/python3.6/site-packages/aiohttp/web_request.py", line 584, in json
    return loads(body)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Graphql playground displayed the following error:
```
{
  "error": "Could not connect to websocket endpoint ws://localhost:8000/graphql. Please check if the endpoint url is correct."
}
```
What I expected:
I expected to see the normal response in graphql playground for a subscription -> 

> Listening ...

**Comment by SmileyChris** [comment]
A major code rewrite has been done, including updating the instructions. Follow the latest instructions and reopen if this is still an issue.
