### ISSUE TITLE
Flask Gevent Example - can't connect from Graphql playground

### ISSUE THREAD

**Issue by dtamez** [graphql-python/graphql-ws#34]
* GraphQL AioWS version: 0.3.0
* Python version: 3.6.5
* Operating System: Linux - Ubuntu 18.04.2 LTS

### Description
Attempting to run the example gevent application and retrieve subscription information in graphql playground.
### What I Did
I am running the example app via app.py in the examples/flask-gevent directory.
python app.py
Server starts and is listening on port 5000.
I then start graphql playground and point it to http://localhost:5000/graphql.
It retrieves the schema correctly as follows:
```
type Query {
  base: String
}

type RandomType {
  seconds: Int
  randomInt: Int
}

type Subscription {
  countSeconds(upTo: Int): Int
  randomInt: RandomType
}
```
I attempt to open up the websocket connection to listen for server updates via:
```
subscription {
   countSeconds
}
```
The server displayed no output whatsoever.
Graphql playground displayed the following error:
```
{
  "error": "Could not connect to websocket endpoint ws://localhost:5000/graphql. Please check if the endpoint url is correct."
}
```
What I expected:
I expected to see the normal response in graphql playground for a subscription ->

`Listening ...`

**Comment by SmileyChris** [comment]
A major code rewrite has been done, including updating the instructions. Follow the latest instructions and reopen if this is still an issue.
