### ISSUE TITLE
wrong version specifier in setup.py

### ISSUE THREAD

**Issue by voidpp** [graphql-python/graphql-ws#41]
This: `graphql-core>=2.0<3` will install `graphql-core-3.1.0b0` which has incompatible changes.

The correct format: `graphql-core>=2.0,<3` or use the compatible release operator:  `graphql-core~=2.0`

How to reproduce:
```
pip instal -r graphql-ws/examples/aiohttp/requirements.txt
python app.py
```

**Comment by Cito** [comment]
Thank you for pointing out the mising comma @voidpp.

I have prepared a fixed version 0.3.1, but currently cannot release because the automatic deployment on PyPI fails. @syrusakbary or @mvanlonden who are the PyPI maintainers need to look into this.

**Comment by SmileyChris** [comment]
Automatic deployment is still failing, I pinged @mvanlonden again on slack

**Comment by SmileyChris** [comment]
And we've got v0.3.1 up finally! :champagne:
