### ISSUE TITLE
How to manage an infinite stream of values in a subscription?

### ISSUE THREAD

**Issue by mandx** [graphql-python/graphql-ws#5]
* GraphQL AioWS version:
    * aiohttp-graphql==1.0.0
    * graphene==2.0.1
    * graphql-core==2.0
    * graphql-relay==0.4.5
    * graphql-server-core==1.0.dev20170322001
    * graphql-ws==0.2.0
    * websockets==4.0.1
    * aiohttp==2.3.6
    * aiohttp-graphql==1.0.0
* Python version: 3.6.3
* Operating System: Ubuntu

### Description
I'm have a subscription going, an `async def` method (like the example in the readme) but it uses `while True` instead of `range`, so it never ends, it is constantly sending (`yield`) new values. I can connect to it using Relay, and I can see the frames coming in DevTools, and I can see the frame telling the GraphQL server to stop on that subscription, and then the frames stop coming.

### The problem
After the `stop` frame I get errors like this in the console:
```
2017-12-27 12:01:43,393 [25768] ERROR    asyncio: Task was destroyed but it is pending!
task: <Task pending coro=<AiohttpSubscriptionServer.on_start() done, defined at ~/.env/lib/python3.6/site-packages/graphql_ws/aiohttp.py:80> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fcb0dc4b918>()]>>
```
And sometime I have to wait a bit for the server to shut down (by hitting `Ctrl-C`), like if there are more "tasks" pending.

This is the subscription class I'm using:
```python
class DataPoint(graphene.ObjectType):
    time = graphene.Float(required=True)
    value = graphene.Float(required=True)


class Subscriptions(graphene.ObjectType):
    graph_data = graphene.List(DataPoint, object_id=graphene.ID(required=True))

    async def resolve_graph_data(self, info, object_id=None):
        time = 0
        logger.debug('>>>>>>>> Start graph')
        while True:
            yield [DataPoint(time=time, value=randint(100, 400))]
            await asyncio.sleep(1.)
            time += 1
        logger.debug('>>>>>>>> End graph')
```
I can see the `Start graph` line being printed, but I never see the `End graph` line.

I guess what we need is some way of "breaking" the `while True:` loop from outside, right?

**Comment by valentinradu** [comment]
I'm hitting exactly this problem. Did you ever manage to solve it. Somehow we should be able to break the while based on if the connection is still open.

**Comment by nguyenlinhlinh** [comment]
I run into the same problem and I solved that by creating another method for unsubscribing. Something like this:
```python
class DataPoint(graphene.ObjectType):
    time = graphene.Float(required=True)
    value = graphene.Float(required=True)

subscribed= False
class Subscriptions(graphene.ObjectType):
    graph_data = graphene.List(DataPoint, object_id=graphene.ID(required=True))
    unsub = grraphene.String()
    async def resolve_graph_data(self, info, object_id=None):
        time = 0
        subscribed = True
        logger.debug('>>>>>>>> Start graph')
        while subscribed:
            yield [DataPoint(time=time, value=randint(100, 400))]
            await asyncio.sleep(1.)
            time += 1
        logger.debug('>>>>>>>> End graph')

     async def resolve_unsub(self,info):
         subscribed = False
         return "Unsubscribed"
```

**Comment by ciscorn** [comment]
@nguyenlinhlinh 
Maybe #13 has solved this issue.

Try the HEAD revisions:

```
pip3 install https://github.com/graphql-python/graphql-core
pip3 install https://github.com/graphql-python/graphql-ws
```

**Comment by SmileyChris** [comment]
This should be fine now in master. Feel free to reopen if you can still reproduce
