### ISSUE TITLE
Django Channels Instructions/Support is Outdated

### ISSUE THREAD

**Issue by singlerider** [graphql-python/graphql-ws#54]
* GraphQL AioWS version: 0.3.1
* Python version: 3.9.0
* Operating System: Ubuntu/Alpine
* Django version: 3.1.2
* Django Channels version: 2.4.0
* ASGIRef version: 3.2.10

### Description

The Django Channels Routing example is outdated:

```
ImportError: cannot import name 'route_class' from 'channels.routing' (/home/MYUSERNAME/.pyenv/versions/3.9.0/envs/ENVNAME/src/channels/channels/routing.py)
```

### What I Did

`route_class` seems to be from `1.1.8x`, which is from 2017. It's too old of a package for me to revert to. There are nested dependencies in Django and Channels. There should at least be an alternative in the instructions on how to achieve the same result in Channels `2.4.0`+.

**Comment by isaacbeatbit** [comment]
I've the same problem

**Comment by SmileyChris** [comment]
I'm successfully using channels with my branched code in #18 
Please give that a go and see if it's working for you. More testing and verification of it working well will give me the confidence to merge it ;)

**Comment by ygbourhis** [comment]
I have an already existing graphql API with:

Python 3.6.8
Django==2.2.6  # I know, I need to update
channels==3.0.2
graphql-ws==0.3.1

And simply nothing works when following the curent documentation.

In the graphql interface with:
`
subscription {
  count_seconds(up_to: 5)
}
`

I get : 
`
{
  "errors": [
    {
      "message": "Subscriptions are not allowed. You will need to either use the subscribe function or pass allow_subscriptions=True"
    }
  ],
  "data": null
}
`

And google is of no help at all.

Is graphql-ws still active and supported?

**Comment by ygbourhis** [comment]
If I follow the doc closely, `from graphql_ws.django_channels import GraphQLSubscriptionConsumer` fails:

```
  File "/home/yves/.virtualenvs/mvp_dashboard/lib/python3.6/site-packages/graphql_ws/django_channels.py", line 6, in <module>
    from channels.generic.websockets import JsonWebsocketConsumer
ModuleNotFoundError: No module named 'channels.generic.websockets'
```

What is the latest channels version supported?

**Comment by SmileyChris** [comment]
Channels v2 now supported on master
