### ISSUE TITLE
Release current master branch to pypi

### ISSUE THREAD

**Issue by hasauino** [graphql-python/graphql-ws#63]
Hello maintainers,
Thank you for this repo :smiley: 
Just wanted to know if you have any plans for releasing the current version of the master branch to PyPI?
Since release 0.3.1 does not include Django sub-module.

**Comment by fabienheureux** [comment]
I recently got write access to this repo and will release a new version this week @hasauino

**Comment by fabienheureux** [comment]
https://pypi.org/project/graphql-ws/ done
