### ISSUE TITLE
Passing the request_context to graphql

### ISSUE THREAD

**Issue by valentinradu** [graphql-python/graphql-ws#7]
Not sure if this is intended or not but shouldn't the context be taken outside the message processing?
In base.py:

```py
def execute(self, request_context, params):
        return graphql(
            self.schema, **dict(params, allow_subscriptions=True))
```

Should be:

```py
self.schema, **dict(params, context_value= request_context, allow_subscriptions=True))
```

Otherwise, how can you pass the `request_context`? Does it make sense to be per message? Or is it intended for another use?

**Comment by colanconnon** [comment]
@valentinradu Are you talking about the django channels implementation?

**Comment by valentinradu** [comment]
Sorry for the late response. No, I'm using it with aiohttp, but this should apply to any implementations.

**Comment by Arfey** [comment]
So guys, we have a good pull request. what does we wait?

**Comment by colanconnon** [comment]
@arfey If you need this now I would just refer that branch directly in your requirements file.

**Comment by dfee** [comment]
In case anyone else comes by this and they don't feel like installing a commit and then falling off the upgrade path... here's a nicer crutch:

```
class ContextualAiohttpSubscriptionServer(AiohttpSubscriptionServer):
    def __init__(self, schema, keep_alive=True, loop=None):
        super().__init__(schema, keep_alive, loop)
        self._check_updated()

    @staticmethod
    def _check_updated():
        import pkg_resources
        import warnings
        from distutils.version import StrictVersion
        graphql_ws_dist = pkg_resources.get_distribution('graphql_ws')
        # https://github.com/graphql-python/graphql-ws/issues/7
        if StrictVersion(graphql_ws_dist.version) > '0.2.0':
            warnings.warn('`graphql_ws` is upgraded, check for `execute` fix')
            import sys; sys.exit() # optional, terminate immediately!

    def execute(self, request_context, params):
        # https://github.com/graphql-python/graphql-ws/issues/7
        params['context_value'] = request_context
        return super().execute(request_context, params)
```

It'll yell at you when `graphql_ws` gets upgraded past 0.2.0 so you can (maybe) upgrade then.

**Comment by SmileyChris** [comment]
Done
